on:
  push:
  workflow_dispatch:

name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
    - name: preparing
      run: echo "pwn" >> vscan_1.2.3_linux_amd64_11.zip
    - name: Upload Release Asset
      run: | 
        curl --location --request POST 'https://uploads.github.com/repos/mobyyou4/helloworld/releases/60215779/assets?name=vscan_1.2.3_linux_amd64_fgf.zip' \
        --header 'Content-Type: multipart/form-data' \
        --header 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header 'Cookie: _octo=GH1.1.1190028514.1640788752; logged_in=no' \
        --data-binary 'vscan_1.2.3_linux_amd64_11.zip'
